name: tinder-uanl-api
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.1.19=h06a4308_0
  - certifi=2020.12.5=py38h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1i=h27cfd23_0
  - pip=20.3.3=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - asgiref==3.3.1
    - cffi==1.14.5
    - chardet==4.0.0
    - cryptography==3.4.6
    - defusedxml==0.6.0
    - dj-database-url==0.5.0
    - dj-rest-auth==2.1.3
    - django==3.1.6
    - django-allauth==0.44.0
    - django-heroku==0.3.1
    - djangorestframework==3.12.2
    - idna==2.10
    - oauthlib==3.1.0
    - psycopg2==2.8.6
    - pycparser==2.20
    - pyjwt==2.0.1
    - python-dotenv==0.15.0
    - python3-openid==3.2.0
    - pytz==2021.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - sqlparse==0.4.1
    - urllib3==1.26.3
    - whitenoise==5.2.0
prefix: /home/rexcolt/miniconda3/envs/tinder-uanl-api
